[package]
name = "thinker-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
async-openai = "0.27.2"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
